"""
Django settings for ToDoList project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kvgx+zl44s7otd15!g9#5@1g+*&_rey)g(ko=hkn$qzocw#(zs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 개발모드인지 운영모드인지 결정    개발모드 True/ 운영모드 False
#기동할 서버의 ip나열: 서버의 ip등록
ALLOWED_HOSTS = []   #[]의 뜻 모든 서버 ip사용 가능
# ALLOWED_HOSTS=[*]  #[*]의 뜻 모든 서버 ip사용 가능

# ex 컴퓨터 192.168.0.5 와 220.221.10.6 인 두대의 컴퓨터에서 운영한다고 한다면
# ALLOWED_HOSTS = [192.168.0.5,220.221.10.6]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'my_to_do_app',
]  #INSTALLED_APPS=[사용할 앱 등록]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 클라이언트 요청 시 url을 확인할 모듈(py파일): manage.py 가 있는 폴더에서 찾는다
ROOT_URLCONF = 'ToDoList.urls'

# html.css.js 등 front에 대한 설정.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # app 폴더를 의미
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ToDoList.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# db 설정: 다른 db를 사용시 설정 변경 해야함
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # mysql등으로 변경하려면 이줄을 변경
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# TIME_ZONE = 'en-us'  # 세계 표준시
# 한국으로 설정한다면 TIME_ZONE='Asia/Seoul'   # 서울 시간으로  설정
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
